import React, { useState, useEffect } from 'react';
import { 
  Calendar, 
  Sparkles, 
  Plus, 
  CheckCircle2, 
  RotateCcw, 
  Clock, 
  BookOpen, 
  Zap,
  TrendingUp,
  AlertCircle,
  Check
} from 'lucide-react';
import api from '../services/api';

export default function StudyPlannerPage() {
  const [planData, setPlanData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [showGenModal, setShowGenModal] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [replanning, setReplanning] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');

  // Form State
  const [title, setTitle] = useState('Midterm Sprint 2026');
  const [availableHours, setAvailableHours] = useState('3');
  const [startTime, setStartTime] = useState('16:00');
  const [endTime, setEndTime] = useState('21:00');
  const [focusSubjects, setFocusSubjects] = useState('');

  const fetchPlan = async () => {
    try {
      const res = await api.get('/planner');
      if (res.data.success) {
        setPlanData(res.data.data);
      }
    } catch (err) {
      console.warn('Planner fetch, using local fallback state.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPlan();
  }, []);

  const handleGenerate = async (e) => {
    e.preventDefault();
    setGenerating(true);
    setErrorMessage('');

    try {
      const res = await api.post('/planner/generate', { 
        title, 
        availableHoursPerDay: Number(availableHours),
        startTime,
        endTime,
        focusSubjects
      });

      if (res.data.success) {
        setShowGenModal(false);
        fetchPlan();
      }
    } catch (err) {
      setErrorMessage(err.response?.data?.error || 'Failed to generate study plan. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  const handleStatusChange = async (id, status) => {
    try {
      await api.put(`/planner/session/${id}`, { status });
      fetchPlan();
    } catch (err) {
      console.error(err);
    }
  };

  const handleReplan = async () => {
    setReplanning(true);
    try {
      await api.post('/planner/replan');
      fetchPlan();
    } catch (err) {
      console.error(err);
    } finally {
      setReplanning(false);
    }
  };

  if (loading) return <div className="glass-card" style={{ padding: '60px', textAlign: 'center' }}>⏳ Loading AI Study Planner...</div>;

  const plan = planData?.plan;
  const sessions = planData?.sessions || [];
  const structuredPlan = planData?.structuredPlan || plan?.ai_metadata;
  const completedCount = sessions.filter(s => s.status === 'Completed').length;
  const progressPct = sessions.length > 0 ? Math.round((completedCount / sessions.length) * 100) : 0;

  return (
    <div className="animate-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
      
      {/* Header bar */}
      <div className="glass-card" style={{ padding: '20px 24px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '16px' }}>
        <div>
          <h2 style={{ fontSize: '1.4rem', fontWeight: 800, display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Calendar style={{ width: '22px', height: '22px', color: '#10b981' }} /> AI Personalized Study Planner
          </h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.88rem', marginTop: '2px' }}>
            Personalized study timetable generated by Gemini AI synced with your exams, due dates, and attendance.
          </p>
        </div>

        <div style={{ display: 'flex', gap: '12px' }}>
          <button className="btn btn-secondary" onClick={handleReplan} disabled={replanning || sessions.length === 0}>
            <RotateCcw style={{ width: '16px', height: '16px', color: '#f59e0b' }} /> {replanning ? 'Replanning...' : 'Replan Remaining'}
          </button>
          <button className="btn btn-emerald" onClick={() => setShowGenModal(true)}>
            <Sparkles style={{ width: '16px', height: '16px' }} /> Generate AI Plan
          </button>
        </div>
      </div>

      {/* Progress & Plan Info Card */}
      <div className="glass-card" style={{ padding: '24px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px', flexWrap: 'wrap', gap: '10px' }}>
          <div>
            <h3 style={{ fontSize: '1.15rem', fontWeight: 700 }}>{plan?.title || 'Active Study Plan'}</h3>
            <span className="badge badge-emerald" style={{ marginTop: '4px' }}>Progress: {completedCount} / {sessions.length} Sessions Completed ({progressPct}%)</span>
          </div>
          <div style={{ textAlign: 'right' }}>
            <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Plan Status</div>
            <span className="badge badge-indigo">{plan?.status || 'Active'}</span>
          </div>
        </div>

        <div style={{ width: '100%', height: '8px', background: 'rgba(255, 255, 255, 0.08)', borderRadius: '4px', overflow: 'hidden' }}>
          <div style={{ width: `${progressPct}%`, height: '100%', background: 'linear-gradient(90deg, #10b981, #06b6d4)', borderRadius: '4px', transition: 'width 0.3s ease' }} />
        </div>

        {/* AI Strategy Summary */}
        {structuredPlan?.summary && (
          <div style={{ marginTop: '16px', padding: '14px 16px', borderRadius: '10px', background: 'rgba(16, 185, 129, 0.08)', border: '1px solid rgba(16, 185, 129, 0.2)' }}>
            <div style={{ fontSize: '0.85rem', fontWeight: 700, color: '#6ee7b7', marginBottom: '4px', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <Sparkles style={{ width: '14px', height: '14px' }} /> AI Strategy Summary:
            </div>
            <p style={{ fontSize: '0.88rem', color: '#f1f5f9', lineHeight: '1.5' }}>
              {structuredPlan.summary}
            </p>
          </div>
        )}
      </div>

      {/* AI Priority Subjects & Recommendations Grid */}
      {structuredPlan && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '20px' }}>
          
          {/* Priorities */}
          {structuredPlan.priorities?.length > 0 && (
            <div className="glass-card" style={{ padding: '20px' }}>
              <h4 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '6px', color: '#f43f5e' }}>
                <Zap style={{ width: '16px', height: '16px' }} /> High Priority Focus Subjects
              </h4>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                {structuredPlan.priorities.map((p, idx) => (
                  <div key={idx} style={{ padding: '10px 12px', borderRadius: '8px', background: 'rgba(255, 255, 255, 0.03)', border: '1px solid var(--border-color)' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                      <span style={{ fontWeight: 700, fontSize: '0.9rem', color: '#fff' }}>{p.subject}</span>
                      <span className="badge badge-rose">{p.priority || 'High'}</span>
                    </div>
                    <p style={{ fontSize: '0.78rem', color: 'var(--text-muted)', marginTop: '4px' }}>{p.reason}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Recommendations */}
          {structuredPlan.recommendations?.length > 0 && (
            <div className="glass-card" style={{ padding: '20px' }}>
              <h4 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '6px', color: '#38bdf8' }}>
                <TrendingUp style={{ width: '16px', height: '16px' }} /> AI Productivity Tips
              </h4>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                {structuredPlan.recommendations.map((rec, idx) => (
                  <div key={idx} style={{ fontSize: '0.85rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'flex-start', gap: '8px' }}>
                    <span style={{ color: '#38bdf8', fontWeight: 700 }}>•</span>
                    <span>{rec}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

        </div>
      )}

      {/* Timetable Session List */}
      <div className="glass-card" style={{ padding: '24px' }}>
        <h3 style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: '16px' }}>Scheduled AI Study Sessions</h3>

        {sessions.length === 0 ? (
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>No study sessions scheduled yet. Click <strong>Generate AI Plan</strong> above to create your schedule.</p>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {sessions.map((s) => (
              <div
                key={s.id}
                style={{
                  padding: '16px',
                  borderRadius: 'var(--radius-sm)',
                  background: s.status === 'Completed' ? 'rgba(16, 185, 129, 0.05)' : 'rgba(255, 255, 255, 0.03)',
                  border: s.status === 'Completed' ? '1px solid rgba(16, 185, 129, 0.2)' : '1px solid var(--border-color)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  flexWrap: 'wrap',
                  gap: '12px'
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
                  <button 
                    onClick={() => handleStatusChange(s.id, s.status === 'Completed' ? 'Pending' : 'Completed')}
                    style={{ background: 'none', border: 'none', cursor: 'pointer', color: s.status === 'Completed' ? '#10b981' : 'var(--text-dim)' }}
                  >
                    <CheckCircle2 style={{ width: '22px', height: '22px' }} />
                  </button>

                  <div>
                    <div style={{ fontWeight: 700, fontSize: '0.96rem', textDecoration: s.status === 'Completed' ? 'line-through' : 'none' }}>
                      {s.topic}
                    </div>
                    {s.reason && (
                      <div style={{ fontSize: '0.8rem', color: '#94a3b8', marginTop: '2px', fontStyle: 'italic' }}>
                        💡 {s.reason}
                      </div>
                    )}
                    <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '4px', display: 'flex', gap: '14px', flexWrap: 'wrap' }}>
                      <span>📚 <strong>{s.subjectName || s.subjectCode || 'Course'}</strong></span>
                      <span>📅 Date: {s.session_date}</span>
                      <span>⏱️ Time: {s.start_time} - {s.end_time}</span>
                    </div>
                  </div>
                </div>

                <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                  <span className={`badge ${s.priority === 'High' ? 'badge-rose' : 'badge-amber'}`}>
                    {s.priority} Priority
                  </span>
                  <span className={`badge ${s.status === 'Completed' ? 'badge-emerald' : 'badge-indigo'}`}>
                    {s.status}
                  </span>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Generate Modal */}
      {showGenModal && (
        <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.75)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100 }}>
          <div className="glass-card" style={{ maxWidth: '500px', width: '100%', padding: '28px' }}>
            <h3 style={{ fontSize: '1.2rem', fontWeight: 800, marginBottom: '16px' }}>Generate AI Study Plan</h3>
            
            {errorMessage && (
              <div style={{ padding: '10px 14px', borderRadius: '8px', background: 'rgba(244, 63, 94, 0.1)', border: '1px solid rgba(244, 63, 94, 0.3)', color: '#fca5a5', fontSize: '0.85rem', marginBottom: '14px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <AlertCircle style={{ width: '16px', height: '16px' }} /> {errorMessage}
              </div>
            )}

            <form onSubmit={handleGenerate} style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
              <div>
                <label style={{ fontSize: '0.8rem', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>Plan Title</label>
                <input type="text" className="input-field" required value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Midterm Sprint 2026" />
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                <div>
                  <label style={{ fontSize: '0.8rem', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>Available Hours / Day</label>
                  <input type="number" min="1" max="12" className="input-field" required value={availableHours} onChange={e=>setAvailableHours(e.target.value)} />
                </div>
                <div>
                  <label style={{ fontSize: '0.8rem', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>Preferred Start Time</label>
                  <input type="time" className="input-field" required value={startTime} onChange={e=>setStartTime(e.target.value)} />
                </div>
              </div>
              <div>
                <label style={{ fontSize: '0.8rem', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>Optional Priority / Focus Subjects</label>
                <input type="text" className="input-field" placeholder="e.g. Data Structures, Calculus III" value={focusSubjects} onChange={e=>setFocusSubjects(e.target.value)} />
              </div>
              <div style={{ display: 'flex', gap: '10px', marginTop: '8px' }}>
                <button type="button" className="btn btn-secondary" style={{ width: '50%' }} onClick={() => setShowGenModal(false)} disabled={generating}>Cancel</button>
                <button type="submit" className="btn btn-emerald" style={{ width: '50%' }} disabled={generating}>
                  {generating ? 'Generating AI Plan...' : 'Generate Plan'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

    </div>
  );
}
